import { chromium } from "playwright-core"
const browser = await chromium.launch({ channel: "chrome", headless: true })
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true })
const errors = []
page.on("pageerror", e => errors.push(e.message))
await page.goto("http://127.0.0.1:5180/", { waitUntil: "networkidle" })
await page.fill("#u", "kousik"); await page.fill("#p", process.env.JOBLAB_PASSWORD ?? "kousik@1209")
await page.click('button[type="submit"]')
await page.waitForSelector(".shell", { timeout: 15000 })
await page.locator('.nav button:has-text("Board")').first().click()
await page.waitForSelector(".job", { timeout: 15000 })
const jobs = await page.locator(".job").count()
const railVisible = await page.locator(".rail").isVisible()
console.log("mobile jobs visible:", jobs, "| rail visible:", railVisible)
await page.screenshot({ path: "../screenshots/mobile-board.png" })
await page.locator(".job").first().click()
await page.waitForSelector(".detail", { timeout: 8000 })
const backVisible = await page.locator(".detail-back").isVisible()
console.log("detail back button visible:", backVisible)
await page.screenshot({ path: "../screenshots/mobile-detail.png" })
await page.locator(".detail-back").click()
await page.waitForTimeout(400)
console.log("returned to list:", await page.locator(".job").first().isVisible())
console.log(errors.length ? "ERRORS: " + errors.join("; ") : "no page errors")
await browser.close()
